name: Docker Publish

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build ./level1/nginx-container -f ./level1/nginx-container/Dockerfile -t $REGISTRY/$IMAGE_NAME:latest

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:latest
- name: Download a Build Artifact
  uses: actions/download-artifact@v3.1.0
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
